### ISSUE TITLE
Feature request: allowing the retrieval models themselves to be prompt optimized

### ISSUE THREAD

**Issue by orionw** [stanfordnlp/dspy#1508]
Hi there!

I'm a newbie to DSPy and am looking to show that our new [Promptriever bi-encoder model](https://arxiv.org/abs/2409.11136) can be optimized via prompts with DSPy.  We did some manual prompt tuning that worked well, but it would be nice to use an automatic method. It seems like the exact method used for LM tuning would work for retrievers as well.

The current docs seem to be focused on LMs being prompt-tuned (which makes sense) but I'm having a hard time finding an example of where I could plug in the retriever as the model and retrieval scores as the metric to optimize. It's quite possible the software already enables it and I am simply missing it :) 

Thanks for your time!

**Comment by arnavsinghvi11** [comment]
Hi @orionw , this is an exciting use case! 

From what I understand, since the Promptriever can be prompted as LMs, you can host the model locally through DSPy-integrated [local LM clients](https://dspy-docs.vercel.app/api/category/local-language-model-clients) and configure your DSPy LM to use this (via `dspy.settings.configure(lm = ...)` as you would with any other LM - [HFClientTGI](https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/hf_client.py) is good for HF hosted models). 

As for the metric, you can use retrieval-type metrics and pass that into the optimizer's metric, resulting in a DSPy pipeline that optimizes the Promptriever on the retrieval metric. The [intro notebook ](https://colab.research.google.com/github/stanfordnlp/dsp/blob/main/intro.ipynb#scrollTo=r3vvHTbnuGBP)has an example of a LM metric (exact match evaluating generation) in tandem with a RM metric (passage match evaluating retrieval quality), but you could simply use retrieval metrics in your case and optimize accordingly. 

Let me know if this helps!
