### ISSUE TITLE
Multiple retriever's as tool use

### ISSUE THREAD

**Issue by dittops** [stanfordnlp/dspy#157]
Is it possible to use multiple retrievers/tools in the same RAG, where the right retriever is opted based on the prompt selection? Is this possible with DSPy? If so, could you please explain/add an example

**Comment by darinkishore** [comment]
Take a look at the forward() method for your pipeline. 

psueodcode-ish: 
```python
Class ChooseBestRetriever(dspy.Module)

def __init__(self, retriever_params) # define all the things you want in your pipeline
    retriever_one = dspy.Retrieve() # set whatever retriever params you want here
    retriever_two = dspy.Retrieve() 
    retriever_three= = dspy.Retrieve()
    choose_retriever = dspy.MultiChainComparison("retriever 1 output, retriever 2 output, retriever 3 output -> best retriever")
    # other modules you need

def forward(self, input): # given input, how should we process it and turn it into the output we want?
    one_output = retriever_one(input)
    two_output = retriever_two(input)
    three_output = retriever_three(input)
    best_retriever = choose_retriever(one_output, two_output, three_output)
    # now that you have best retriever, figure out what to do with it
```

How do the retrievers differ? That informs how you use them in your pipeline. If they differ significantly, I'd suggest making different small DSPy programs for each retriever. 

The proper retriever choosing will be handled in the Teleprompter.compile() stage based on your metric you've chosen. I would suggest compiling examples for the input/output for determining best retriever for your current task. This will likely be difficult. You should be fine with 3-8 examples for train and dev set. 

The metric function will evaluate the results of this pipeline, and will be passed to teleprompter.compile() It should evaluate the choose_retriever. Think about how to evaluate if it's a good retriever based on the passages you get. This metric function may be complex, depending on how much you care. If you really want to have a good metric, use another DSPy program as the metric, possibly teleprompted on llama-2 or 3.5-turbo. You'd likely have to think about how you want that to be done as well. A simple metric, without creating another program, could be a hand-crafted GPT evaluation function, which will work okay and not cost too much because you probably don't have 500/0 examples ready to go. 

It could look something like this:
```python
def best_passage_metric(gold_passage:str, passages:list):
    """
    Determine if the selected passage is the most relevant passage to query from a list. . 
    :param gold_passage: gold passage
    :param passages: list of passages
    :return: pass or fail
    """
    # call GPT
    system_prompt = "You are an expert technical evaluator who is consistent, deterministic, and reliable."
    user_prompt = "Determine if the gold passage is the most relevant passage for the query 'What is the meaning of life?'. Think step by step, and output a function call with your judgement at the end"
    user_prompt += f"#Gold Passage: {gold_passage}\n\n"
    passages.remove(gold_passage)

    for i, passage in enumerate(passages):
        if passage != gold_passage:
            user_prompt += f"Alternative Passage {i}:\n {passage}\n\n"

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": f"{system_prompt}"},
            {"role": "user", "content": prompt},
        ],
        temperature=0,
        functions={
            "name": "is_best_passage",
            "description": "Output if the gold passage is the most relevant passage for the query.",
            "parameters": {
                "type": "object",
                "properties": {
                    "evaluation": {
                        "type": "string",
                        "description": "yes or no"
                    }
                }
            }
        }
    )

    if response["function_call"]["arguments"]["evaluation"] == "yes": # maybe wrong args to get
        return True
    return False
```

Although, the complicated-ness of that function poses a pretty decent argument as to just using DSPy to code up the metric. Your choice!

I may be wrong about some things, so if someone from the team could verify, would be lovely. Please let me know if you have any more questions for your use-case and I'd be happy to brainstorm with you.

**Comment by darinkishore** [comment]
lemme know. don't take it too heavily, it honestly felt pseudo-code-y aside from the gpt-eval. watch out for eval costs if ur running gpt-4.
