### ISSUE TITLE
How to increase maximum length of tokens?

### ISSUE THREAD

**Issue by alessarcross** [stanfordnlp/dspy#169]
My prompt outputs are on the longer side, and often the (output) text is cut off. Is there a way to adjust the max length of tokens? Thank you.

**Comment by okhat** [comment]
Yes, set `max_tokens` in the LM initialization. You can also do it per module if you want.

**Comment by ujjawal-ti** [comment]
Hi @okhat ,
I have initialized my LM as HFModel, like below
`llm_mistral = dspy.HFModel(model = model_name)`

Also, tried `llm_mistral = dspy.HFModel(model = model_name,max_tokens=4000)`
But getting the below error likely due to the missing key `max_tokens `in `kwargs`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 3
      1 model_name='mistralai/Mistral-7B-Instruct-v0.1'
      2 max_tokens=4000
----> 3 llm_mistral = dspy.HFModel(model = model_name,max_tokens=4000)
      4 # This sets the language model for DSPy.
      5 dspy.settings.configure(lm=llm_mistral)

TypeError: HFModel.__init__() got an unexpected keyword argument 'max_tokens'

**Comment by jianlins** [comment]
dspy.ChainOfThought('question -> answer', max_tokens=4000)

**Comment by desaianm** [comment]
dspy.ChainOfThought('question -> answer', max_tokens=4000) this worked for me

**Comment by bhatt-priyadutt** [comment]
@jianlins i dont see it working for dspy.TypedChainOfThought('question -> answer', max_tokens=4000)
