### ISSUE TITLE
Unable to run o1-mini (azure, dspy==2.5.34)

### ISSUE THREAD

**Issue by denisergashbaev** [stanfordnlp/dspy#1847]
Hello! I am getting the following error when trying to run o1-mini with DSPy==2.5.34 with this config:

```
dspy.configure(experimental=True)
lm = dspy.LM(model="azure/gpt-o1-mini", ...)
```

error: 
```
{'error': {'message': "Unsupported value: 'message...support 'system' with this model."
```

Any ideas?

**Comment by okhat** [comment]
Hey @denisergashbaev !

I think via OpenAI, the o1 model works, but perhaps not via Azure?

Anyway if the issue is that it Azure o1 can't handle "system" roles, the easiest fix (it's 3-4 lines) is to build an adapter that inherits from ChatAdapter and just switches the "system" role to a "user" role.

**Comment by okhat** [comment]
Closing under the assumption that this is resolved. Feel free to reopen
