### ISSUE TITLE
runtime cache

### ISSUE THREAD

**Issue by DmitriyG228** [stanfordnlp/dspy#213]
Hey, I have noticed that in order to avoid redundant model calls cash is being stored. Hove can I control this behaviour?

**Comment by okhat** [comment]
Sure what kind of control are you looking for?

**Comment by DmitriyG228** [comment]
I would want to drop it

**Comment by okhat** [comment]
Completely drop the cache?

**Comment by okhat** [comment]
Just switch this line to false:

https://github.com/stanfordnlp/dspy/blob/87e58d943c93766f08ccfe3b4c35d689c32bd7d8/dsp/modules/cache_utils.py#L10C1-L11C1

**Comment by DmitriyG228** [comment]
can I ignore cash while calling a pipeline?

**Comment by okhat** [comment]
Yeah

**Comment by UtkarshGarg-UG** [comment]
Hi, I am observing a behavior where even though my module has been updated using signature optimizer, the evaluator runs from the cache and gives me the same score. Is there a way to run the evaluator without it reusing the result from cache? It shouldn't in the first place because compiled_prompt_opt has an updated signature below using the MIPRO optimizer.

print(evaluator(compiled_prompt_opt, devset=devset, )

**Comment by jasonmgeorge** [comment]
> I would want to drop it

I was able to locate my local cache directory (to delete it) with the following
`import dsp
from dsp.modules.cache_utils import CacheMemory
print(CacheMemory)`

Note that there are a few other memory locations in cache_utils that might be in use.

Required a reload of my local Jupyter Notebook to take effect.
