### ISSUE TITLE
using "Tools" with DSPy — ReAct assumes .passages

### ISSUE THREAD

**Issue by roolio** [stanfordnlp/dspy#276]
Hello, 

I would like to know if adding _tools_ to a DSPY module is easy. 
By "tools" here I mean tools as e.g. implemented in Langchain [here](https://python.langchain.com/docs/modules/agents/tools/custom_tools) 

I've seen in the react.py modules that tools can be added, but I ignore how to implement such (e.g as simple one that give current time).  I can very naively make a module with deterministic forward pass 

```
class GiveTime(dspy.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self):
        current_time = datetime.datetime.now().strftime("%H:%M:%S")
        return current_time
```

so in fact the real question is : how to I tell other modules they can use this when need to know current time. That's why I was searching towers React. 

Do you have a notebook of use of the react.py module?

many thanks in advance, and kudos for DSPy! It made my last 2 weeks :)

**Comment by okhat** [comment]
Hey @roolio ! Thanks for this question.

So far we've played with a small number of tools (retrievers, SQL, and python interpreter) but we'd love to support more.

In general, supporting tools in DSPy is very easy because DSPy is just Python control flow + some modules for prompting (e.g., dspy.ChainOfThought) and some modules for optimizers. However, tools for dspy.ReAct specifically need a particular structure that's not too well-document right now.

We need help build some examples with this and make it better. But here's some initial thoughts:

- Your GiveTime module is great. Technically you can just make it a function (one line) and call it inside your DSPy program when needed!
- If you want to use this with dspy.ReAct, then usage would be like:

```
mytool = MyTool()
gen = dspy.ReAct('question -> answer', tools=[mytool])
```

where MyTool is:

```
class GiveTime:
    name = "GiveTime"
    input_variable = "empty"
    desc = "takes an empty string and returns the current local time"

    def __init__(self, k=3):
        pass
   
    def __call__(self, *args, **kwargs):
        return datetime.datetime.now().strftime("%H:%M:%S")
```

I had to say `empty` since we hadn't thought of taking zero arguments!

**Comment by aymeric-roucher** [comment]
I had the same error due to `.passages` and same resolution by removing it as @roolio above!

**Comment by nr-bailey** [comment]
Hello, 

I would like to know whether there is any support for passing **multiple inputs** to a tool.

I've tried defining a Pydantic model, and then defining the input_variable accordingly - but I find this sometimes fails, and I'd prefer something more reliable.

Thank you in advance!! DSPy is fantastic, hoping to just get over this one last hurdle :)
