### ISSUE TITLE
Couple high level questions

### ISSUE THREAD

**Issue by alsozatch** [stanfordnlp/dspy#277]
DSPy looks like a great tool that I'm looking into. I watched the YouTube intro which explained a lot, but I'm wondering 2 things:

1. Performance/speed. I didn't see anything about the speed of running the LLM with DSPy, does it make it considerably slower? Have there been any speed tests?
2. How does DSPy interact with LoRA? Is DSPy strictly interacting with the prompting of the LLM, so theoretically you could achieve the same effect as DSPy if you threw prompt engineers at the problem for some length of time? In which case I assume LoRA woudl be entirely separate and something you would do before compiling the DSPy program. 

Please let me know if you have any thoughts. Thanks!

**Comment by okhat** [comment]
DSPy helps speed in the sense that it can teach small models to solve complex tasks. Otherwise, the actual latency of each LM call is dictated entirely by the LM provider like OpenAI or local LM server you're using, like TGI or VLLM. DSPy doesn't affect that time directly.

LoRA definitely applies to DSPy in the sense that we support finetuning on automatic demonstrations, but we need more infrastructure support in that direction.

See this notebook: https://github.com/stanfordnlp/dspy/blob/main/examples/qa/hotpot/multihop_finetune.ipynb

**Comment by alsozatch** [comment]
Thanks. So even with multiple CoT and Retrieve, etc. there is only 1 LM call?

**Comment by okhat** [comment]
No, each module will make it own call. (Retrieve doesn't call the LM.)
