### ISSUE TITLE
Does metric have to return `bool`?

### ISSUE THREAD

**Issue by breakds** [stanfordnlp/dspy#298]
I am thinking about writing a program for a "batch processing" task, i.e., each call to the program, there will be a list of inputs, and the output is a corresponding list for the inputs. To optimize such a program, a natural metric would be something like "out of the 20 inputs, how many of them are correctly answered?".

I think in this case, I probably need a numerical metric instead of bool metric. Is that right? If so, do you think it is good to extend metric for this?

Thanks!

**Comment by breakds** [comment]
I was reading https://github.com/stanfordnlp/dspy/blob/main/dspy/teleprompt/bootstrap.py#L145 and it seems to suggest that the metric is treated as a `bool` anyway. Did I miss anything?

Thanks!

**Comment by okhat** [comment]
Yeah this only affects how few shot examples are created. It doesn’t affect anything else!

**Comment by grand-cat-unknown** [comment]
@okhat  can you elaborate a bit on this please? "Yeah this only affects how few shot examples are created. " 

Let's say I have a metric that returns values from 1 to 10. 1 being low similarity and 10 being high. 
Can I incorporate this somehow as a metric? or do I need to threshold my score somehow and return a bool ?

**Comment by okhat** [comment]
Sorry I'm adding material about this to the docs.

There's a couple of examples of this, here's one: https://github.com/stanfordnlp/dspy/blob/main/examples/tweets/tweet_metric.py

```python
def metric(gold, pred, trace=None):
    question, answer, tweet = gold.question, gold.answer, pred.output
    context = retrieve(question).passages

    engaging = "Does the assessed text make for a self-contained, engaging tweet?"
    faithful = "Is the assessed text grounded in the context? Say no if it includes significant facts not in the context."
    correct = f"The text above is should answer `{question}`. The gold answer is `{answer}`."
    correct = f"{correct} Does the assessed text above contain the gold answer?"
    
    with dspy.context(lm=gpt4T):
        faithful = dspy.Predict(Assess)(context=context, assessed_text=tweet, assessment_question=faithful)
        correct =  dspy.Predict(Assess)(context='N/A', assessed_text=tweet, assessment_question=correct)
        engaging = dspy.Predict(Assess)(context='N/A', assessed_text=tweet, assessment_question=engaging)

    correct, engaging, faithful = [m.assessment_answer.lower() == 'yes' for m in [correct, engaging, faithful]]
    score = (correct + engaging + faithful) if correct and (len(tweet) <= 280) else 0

    if trace is not None: return score >= 3
    return score / 3.0
```

The last two lines are what matters.

Basically:

1. If `trace` is `None` (i.e., if we're *not* creating few-shot examples), it returns a float, in this case `score / 3.0`. It doesn't have to be out between 0.0 and 1.0 but it's nice for your own sanity. This is a `float` because, during optimization or evaluation, we want to find the average score overall.
2. Otherwise (i.e., if we *are* creating few-shot examples), it returns a `bool` with a threshold (`score >= 3`). This is a `bool` because we need to know whether or not this example is, ultimately, worthy of using as a demonstration.

Does this make sense?

**Comment by grand-cat-unknown** [comment]
Thanks for the quick and detailed reply!
It doesn't make complete sense to me yet, but I think I get the essence of it.

 I just have to get comfortable with the library and the paradigm a bit more. Thank you so much for the great work! 
 This library is really what I was looking for.
