### ISSUE TITLE
DSPy framework and support for AWS BedRock

### ISSUE THREAD

**Issue by deepuak** [stanfordnlp/dspy#487]
hi,

Can someone please let me know whether **DSPy** framework support models hosted on **AWS Bedrock**? And can I use `dspy.OpenAI() `for Bedrock as well? It would be really great if someone can share me an example of `dspy.OpenAI() `with bedrock endpoint.

**Comment by arnavsinghvi11** [comment]
Hi @deepuak , 

DSPy supports AWS Bedrock! Check out [dspy.Bedrock](https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/bedrock.py) and the underlying [AWSLM](https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/aws_lm.py) class.

You can use this directly `dspy.Bedrock(region_name=..., model=..., ...)` instead of `dspy.OpenAI()`.

**Comment by deepuak** [comment]
thank you!

**Comment by subhsaha** [comment]
Documentation - [DSPy AWS Provider](https://dspy-docs.vercel.app/api/language_model_clients/aws_providers)

**Comment by monicaguduru** [comment]
The above documentation returns 404 NOT_FOUND. Has it been moved to a different place or does dspy not provide with AWS Bedrock anymore?

**Comment by ryanpeach** [comment]
> The above documentation returns 404 NOT_FOUND. Has it been moved to a different place or does dspy not provide with AWS Bedrock anymore?

Same question

**Comment by okhat** [comment]
Just use dspy.LM, see the landing page dspy.ai at the top!

**Comment by okhat** [comment]
Finetuning is only supported for local models, openai, databricks, and anyscale

**Comment by ryanpeach** [comment]
IMO you should reopen the ticket, since most of the best features of bedrock are not supported.

**Comment by fabriziodimino** [comment]
Try to use: 
lm = dspy.LM('bedrock/us.amazon.nova-pro-v1:0')
dspy.configure(lm=lm)

**Comment by BTripp1986** [comment]
This thread is throwing off LLMs. I have had multiple LLMs reference this thread, adamant that dspy.Bedrock exists instead of using dspy.LM as described by @fabriziodimino .

**Comment by xbno** [comment]
same. had to explicitly show gemini your answer to convince it that dspy.LM for bedrock is the right way. so hopefully my response will reinforce that further :)

**Comment by ViswanathaReddyGajjala** [comment]
> Finetuning is only supported for local models, openai, databricks, and anyscale

Does anyone have insight into how complex it would be to add support for Bedrock? I’m interested in hearing opinions.

**Comment by mbdeniz** [comment]
> > Does anyone have insight into how complex it would be to add support for Bedrock? I’m interested in hearing opinions.
> 
> Bedrock is already supported, I'm using it currently. Here is an example:

@BTripp1986  how do you pass the boto client? this is how I normally authenticate


prod_session = boto3.session.Session(profile_name="data-prod")
client = prod_session.client(
    "bedrock-runtime",
    region_name=AWS_REGION
)

**Comment by BTripp1986** [comment]
> > > Does anyone have insight into how complex it would be to add support for Bedrock? I’m interested in hearing opinions.
> > 
> > 
> > Bedrock is already supported, I'm using it currently. Here is an example:
> 
> [@BTripp1986](https://github.com/BTripp1986) how do you pass the boto client? this is how I normally authenticate
> 
> prod_session = boto3.session.Session(profile_name="data-prod") client = prod_session.client( "bedrock-runtime", region_name=AWS_REGION )

You don't actually instantiate a boto3 client. There _might be_ a way to pass in a client, but I can't offer any guidance there because I have not used it that way. The thing to keep in mind is that DSPy uses Litellm under the hood to interact with model providers, so their docs will probably be most helpful for this.  

Looking at the [Litellm documentation for bedrock](https://docs.litellm.ai/docs/providers/bedrock) it shows only examples of using env vars to pass in client settings. So your snippet would look like this:
```python
os.environ["AWS_PROFILE"] = "data-prod"
os.environ["AWS_REGION"] = AWS_REGION

lm = dspy.LM("bedrock/some-model")
dspy.configure(lm=lm)
```

That example should work to get you going, but for most deployments it would be better to set these as env vars externally rather than setting them in the source code.
