### ISSUE TITLE
Deeplake retriever import issue for openai.error

### ISSUE THREAD

**Issue by SID-SURANGE** [stanfordnlp/dspy#592]
While playing around dspy with DeepLake as retriever I encountered an import issue for below code from dspy/retrieve/deeplake_rm.py - 

```
    import openai.error

    ERRORS = (
        openai.error.RateLimitError,
        openai.error.ServiceUnavailableError,
        openai.error.APIError,
    )
```

Seems openai as deprecated using openai.error and is now using openai.[error-type]. My current openai version - 1.13.3

Reference - https://platform.openai.com/docs/guides/error-codes/handling-errors

**Comment by arnavsinghvi11** [comment]
Hi @SID-SURANGE , which openai error were you getting? Currently `"openai>=0.28.1,<2.0.0"` are supported when installing `dspy-ai`. It seems like this works fine for current wrappers like [gpt3.py](https://github.com/stanfordnlp/dspy/blob/226a0d94672f03a5d33215c5efce473a1a3419be/dsp/modules/gpt3.py#L27) that have similar openai error logic (but it could be due to the whichever of the 3 errors you're receiving)
