### ISSUE TITLE
ColBERTv2 index over the Wikipedia 2017 abstracts dataset from HotPotQA

### ISSUE THREAD

**Issue by Ren-Xin** [stanfordnlp/dspy#633]
When I need to deploy my RM locally, where should I go to get Wikipedia for hotpotqa datasets and models? I have deployed colbertv2 locally, but there is no Wikipedia 2017 "abstracts"

**Comment by arnavsinghvi11** [comment]
Hi @Ren-Xin , this is likely a question for the official[ ColBERT repo ](https://github.com/stanford-futuredata/ColBERT) but you can use a server that is already hosting the Wiki 2017 abstracts search index
`colbertv2_wiki17_abstracts = dspy.ColBERTv2(url='http://20.102.90.50:2017/wiki17_abstracts')`

lmk if that helps!

**Comment by psych0v0yager** [comment]
@arnavsinghvi11 Where can the code to start this server be located inside the repo? Also can we switch the url out for another url to use Colbertv2?

**Comment by willy-b** [comment]
@Ren-Xin 
FYI since I have had timeouts using the official Wikipedia 2017 abstracts server at ( `http://20.102.90.50:2017/wiki17_abstracts` ; though it almost always works great!), I was also looking for this, as I was specifically testing with HotPotQA where the tutorials reference this dataset.

Thus I can share that it seems one can get that data by following instructions at [https://github.com/stanford-futuredata/Baleen/blob/936c50540ce92d307a5d612c745fc046575285fa/README.md?plain=1#L35](https://www.google.com/url?q=https://github.com/stanford-futuredata/Baleen/blob/936c50540ce92d307a5d612c745fc046575285fa/README.md?plain%3D1%23L35&sa=D&source=calendar&usd=2&usg=AOvVaw1hYuEq0Nsqq4fHnW53KRBJ) .

(I didn't find a prebuilt ColBERTv2 index one can download for the Wikipedia 2017 abstracts yet, but at least one can index the data yourself if you need to.)

```
# Preprocessed Wikipedia Abstracts 2017 collection (1 GB compressed)
wget https://downloads.cs.stanford.edu/nlp/data/colbert/baleen/wiki.abstracts.2017.tar.gz
tar -xvzf wiki.abstracts.2017.tar.gz
```
For official guidance on how to index and serve that in `ColBERTv2` you can see their official example notebook:
[https://colab.research.google.com/github/stanford-futuredata/ColBERT/blob/main/docs/intro2new.ipynb](https://www.google.com/url?q=https://colab.research.google.com/github/stanford-futuredata/ColBERT/blob/main/docs/intro2new.ipynb&sa=D&source=calendar&usd=2&usg=AOvVaw0NxJP8wifGw_bf4AtPZaYQ) .

**It has > 5 million documents so will probably take quite some time to index depending on your settings.**
I confirmed I could sample 1000 documents from it and index it, serve it, and access from DSPy (I used the tutorial default ColBERTv2 checkpoint and settings which could be improved upon):
![Screenshot_20240917_133902](https://github.com/user-attachments/assets/0ce0130e-8b77-4a26-a9c9-ddde49498d97)
![Screenshot_20240917_133812](https://github.com/user-attachments/assets/c55e1844-3754-48ff-adc3-0adca2fb8c14)
![Screenshot_20240917_132959](https://github.com/user-attachments/assets/28475e05-17fe-412c-8fd1-4c45620134b2)
Note that to run the index locally using `server.py` and retrieve from `DSPy` I had to modify the metadata.json / index configuration to reference the collection text so it could return the actual documents not just the indices of the documents; that was not the configuration by default.
![Screenshot_20240917_143103](https://github.com/user-attachments/assets/4b177498-b921-498b-9ed0-8e81f1b0a151)
![Screenshot_20240917_143124](https://github.com/user-attachments/assets/afd5764d-0134-41e4-abef-2abc43270a5e)
![Screenshot_20240917_143148](https://github.com/user-attachments/assets/7a74632d-84d0-40b3-a55e-2f32f207a67f)

Compare outputs from the servers for overlapping content:
```
# local (I did not concatenate the title before body text ("{title} | ") before indexing my 1000 document sample)
/content# curl 'http://127.0.0.1:8893/api/search?query=William%20Henry%20Furman&k=1'
{"query":"William Henry Furman","topk":[{"pid":931,"prob":1.0,"rank":1,"score":25.9375,"text":"William Henry Furman is an American convicted felon who was the central figure in \"Furman v. Georgia\", the case in which the United States Supreme Court outlawed most uses of the death penalty in the United States."}]}

# DSPy team recommended hosted ("{title} | " added before article content in their case)
/content# curl 'http://20.102.90.50:2017/wiki17_abstracts?query=William%20Henry%20Furman&k=1'
{"topk":[{"text":"William Henry Furman | William Henry Furman is an American convicted felon who was the central figure in \"Furman v. Georgia\", the case in which the United States Supreme Court outlawed most uses of the death penalty in the United States.","pid":932,"rank":1,"score":28.151994705200195,"prob":1.0,"long_text":"William Henry Furman | William Henry Furman is an American convicted felon who was the central figure in \"Furman v. Georgia\", the case in which the United States Supreme Court outlawed most uses of the death penalty in the United States."}],"latency":130.1407814025879}
```

---
2025 EDIT, adding context since I note on my GitHub I do NOT use AI coding assistance, and this comment may have confused a reader that I was or am using coding assistance for work on my GitHub (I am not and have not been). Most readers can stop here.
To be clear: (1) None of the code published on my GitHub has to do with DSPy or this comment, (2) the comment above came out of a tutorial I was working through for a class requiring us to do retrieval augmented generation (RAG) (not coding assistance) with DSPy (using a frozen existing simple language model with an existing simple retrieval model (RM), without reflection or reasoning steps).
I used DSPy as it was a required part of Stanford XCS224U (though I recommend both the course and DSPy for RAG) to write python to do RAG using DSPy so I was working though the associated tutorials.  It was used in the original sense of DSP as Demonstrate Search Predict, the original definition of DSP in DSPy before the project evolved, see https://arxiv.org/abs/2212.14024v2 : `Retrieval-augmented in-context learning has emerged as a powerful approach for addressing knowledge-intensive tasks using frozen language models (LM) and retrieval models (RM). Existing work has combined these in simple "retrieve-then-read" pipelines in which the RM retrieves passages that are inserted into the LM prompt. To begin to fully realize the potential of frozen LMs and RMs, we propose Demonstrate-Search-Predict (DSP)` .  That is, a store of documents was being searched using ColBERTv2 (e.g. Wikipedia) for those semantically similar to a query, then an LLM answers a question based on the retrieved documents, or summarizes them. I used this for a class, and it is not related to any work published on my own GitHub (did not publish anything related to or derived from that assignment online; though a very different assignment from that same course led to a paper and a project on my GitHub not using this tool, https://github.com/willy-b/RASP-for-COGS ) Indexing documents using an existing retrieval model (RM) or querying that retrieval model should not be confused with training a RM or LLM.

Separately, https://github.com/i-am-ying-li (which is personal, non-professional, non-academic ), may eventually use either DSP(y) or something similar as an add on not for coding assistance (only emphasizing since the newer name Declarative Self-improving Python sounds like it to some), but for improved RAG, as during the course I was impressed with how well DSPy works for this. But currently DSP(y) is not in use by Ying Li or me anywhere and has not since the required period during the 2024 course, which was using a frozen existing simple language model with an existing simple retrieval model, without reflection or reasoning steps.

**Comment by vincentkoc** [comment]
After MUCH pain dealing with realiable sources for this dataset i cooked a version using a cached version of the JSON which is pre-chunked, compressed and in vector format. From 3-4gb down to ~500mb. Can grab here https://huggingface.co/datasets/Comet/wikipedia-2017-bm25
