### ISSUE TITLE
pytest failing in dev container

### ISSUE THREAD

**Issue by drawal1** [stanfordnlp/dspy#739]
ImportError while importing test module '/workspaces/dspy/tests/teleprompt/test_mipro_optimizer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/teleprompt/test_mipro_optimizer.py:4: in <module>
    import dspy
dspy/__init__.py:1: in <module>
    import dsp
dsp/__init__.py:1: in <module>
    from .modules import *
dsp/modules/__init__.py:1: in <module>
    from .anthropic import Claude
dsp/modules/anthropic.py:5: in <module>
    import backoff
E   ModuleNotFoundError: No module named 'backoff'

**Comment by drawal1** [comment]
After doing a 'pip install .', I get No module named 'structlog'

**Comment by drawal1** [comment]
Optional dependencies for dspy.Bedrock are not specified anywhere. Should we setup a group in toml for each module?

**Comment by drawal1** [comment]
> Optional dependencies for dspy.Bedrock are not specified anywhere. Should we setup a group in toml for each module?

This module should probably be removed once LiteLLM is integrated

**Comment by okhat** [comment]
Thank you @drawal1 ! Can we tag the relevant people here? The dev container was just merged last week

**Comment by drawal1** [comment]
@Joshmantova - can you take a look at build fail due to backoff and structlog? ignore the posts re. bedrock

**Comment by josh-mantovani** [comment]
> @Joshmantova - can you take a look at build fail due to backoff and structlog? ignore the posts re. bedrock

Yup, I'll get a fix up today. This also pushes the priority of getting dev container tests in CI. For now, just install the package manually within your container but I'll fix it shortly. Thanks for bringing it to my attention!

**Comment by Joshmantova** [comment]
@drawal1 - this actually isn't a bug. When a Python interpreter is selected in VSCode for a given workspace, it will remember the interpreter you chose until you choose a different one. It doesn't look like there's a way to override the interpreter chosen if one has previously been selected for the workspace. To resolve the issue, you need to be using the Poetry virtual env python interpreter rather than whichever one you currently have selected.

To do this, follow the instructions here and select the Poetry interpreter. I'll throw up a PR to make this a little easier and include [these instructions](https://code.visualstudio.com/docs/python/environments#_working-with-python-interpreters) but this will fix the issue and once you select the correct interpreter once, it'll remember it moving forward.
