### ISSUE TITLE
Would suggest COPRO ignore "return_outputs" 

### ISSUE THREAD

**Issue by oekekezie** [stanfordnlp/dspy#767]
If "return_outputs" is set to true in the eval_kwargs, the evaluator will return a tuple with examples, prediction, and score I believe. If you accidentally include this parameter when using COPRO you'll get an error like this: **TypeError: '>' not supported between instances of 'Example' and 'Example'**. 

Removing the parameter resolved the issue. I'm wondering if it might make sense to have COPRO ignore the return_outputs parameter when calling an evaluator so that other folks don't run into this issue?

**Comment by arnavsinghvi11** [comment]
Hi @oekekezie , thanks for raising this issue. 

I'm pretty sure this is because `return_outputs` returns a tuple of the evaluation score and a list of outputs with Example types (which is handled in various conditions within Evaluate [here](https://github.com/stanfordnlp/dspy/blob/696f2d2e1f96f173abb36302c71a725d564dfadb/dspy/evaluate/evaluate.py#L228))
but those return types are not accounted for in COPRO's [evaluate call](https://github.com/stanfordnlp/dspy/blob/696f2d2e1f96f173abb36302c71a725d564dfadb/dspy/teleprompt/copro_optimizer.py#L223C21-L223C83) which only returns a score, likely triggering the error in the [comparison](https://github.com/stanfordnlp/dspy/blob/696f2d2e1f96f173abb36302c71a725d564dfadb/dspy/teleprompt/copro_optimizer.py#L236).

lmk if this is indeed the issue and if adding that condition within COPRO handles it. Feel free to push a PR for it if so or share your program and stack trace so we can take a closer look. Thanks again for finding this!

**Comment by oekekezie** [comment]
Yep, that's exactly my understanding as to why the error occurred as well. I just got rid of the flag and it worked perfectly fine. I'm actually a physician who's just playing around with this stuff for fun so I'm not too sure what you mean by "push a PR"--I know just enough Git to be dangerous but not sure you want me directly contributing code if that's what you mean :)
