### ISSUE TITLE
session crashed in colab with hf models like Llama-2-7b-hf 

### ISSUE THREAD

**Issue by anushka192001** [stanfordnlp/dspy#994]
when i am trying to use https://huggingface.co/meta-llama/Llama-2-7b-hf using

TEMPERATURE = 0.1
DO_SAMPLE = False 
llama_2_7b = dspy.HFModel(model = 'meta-llama/Llama-2-7b-hf', model_kwargs={'trust_remote_code': True, 'temperature': TEMPERATURE, 'do_sample': DO_SAMPLE})

 on my basic colab version(unpaid) (which has only 12 gb ram and 104 gb disk size) 

then when i am compiling the dspy program then i am getting session crashed problem and ram is getting utilized to its full capapcity.

so please tackle this, this is hindering my experiments

**Comment by rishabgit** [comment]
Hey! I understand this issue is affecting the experiments you're running for your work, but I think pulling email IDs of all the existing contributors and emailing them with zero wait is crossing some boundaries.

Requesting fixes is definitely not unreasonable and very much encouraged (e.g., you found out edge cases which weren't caught before), but to bump up an issue, I'll suggest tagging relevant people (usually the active devs but use git blame otherwise) in the comments AFTER waiting at least a couple of days or a week.

![image](https://github.com/stanfordnlp/dspy/assets/52187856/4decd4e0-2961-43e1-89d4-408fdbc2d386)

**Comment by KE7** [comment]
😩 the email was not necessary

**Comment by KE7** [comment]
Doing some back of the envelope math, your issue is you need a bigger GPU or use a quantized model that fits

**Comment by anushka192001** [comment]
@KE7  can you suggest  some opensource huggingface  quantized models best for classification tasks?

**Comment by thomasahle** [comment]
Closing this, since by @KE7's calculations it's a problem of using a too large model on a too small GPU.

If this is about something else, like DSPy's error messages needing improvement, please open a new issue, or contribute to an existing one.
